export const LOADFIREBALLDATA = 'LOADFIREBALLDATA';
export const LOADNEODATA = 'LOADNEODATA';
export const SHOWNEODATA = 'SHOWNEODATA';
export const TEST = 'TEST';
export const GETDATE = 'GETDATE';
export const SLIDERCHANGE = 'SLIDERCHANGE';
